<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RootNamespace>UCP_1_Revisi</RootNamespace>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<NoWarn>NU1603;NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExcelDataReader" Version="3.9.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.9.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WinForms" Version="150.1652.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
		<PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.20110.1" />
	</ItemGroup>

</Project>